# Generated by Django 6.0.3 on 2026-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_auth', '0002_department_oauser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
