# Generated by Django 6.0.3 on 2026-04-07 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oa_auth', '0002_department_oauser_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_notifications', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='notifications', to='oa_auth.department')),
            ],
        ),
    ]
